# Generated by Django 2.2.17 on 2021-03-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.CharField(default='', max_length=128),
        ),
    ]
