# Generated by Django 2.2.17 on 2021-03-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0004_vote_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
    ]
