# Generated by Django 2.2.17 on 2021-03-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0005_remove_vote_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='userprofile',
        ),
    ]
