# Generated by Django 2.2.17 on 2021-03-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0007_auto_20210322_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='image_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
