# Generated by Django 2.2.17 on 2021-03-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0008_vote_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AlterField(
            model_name='vote',
            name='image_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
