# Generated by Django 2.2.17 on 2021-03-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0009_auto_20210324_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
