# Generated by Django 2.2.17 on 2021-03-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0010_vote_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voteType',
            field=models.CharField(default='', max_length=128),
        ),
    ]
