# Generated by Django 2.2.17 on 2021-03-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0011_vote_votetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voteType',
        ),
    ]
