# Generated by Django 2.2.17 on 2021-03-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0012_remove_vote_votetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_id',
            field=models.CharField(default=1, max_length=128, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
