# Generated by Django 2.2.17 on 2021-03-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0013_auto_20210325_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='image_id',
            new_name='vote_type',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='username',
        ),
    ]
