# Generated by Django 2.2.17 on 2021-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0014_auto_20210325_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(max_length=128)),
                ('next', models.CharField(max_length=128)),
            ],
        ),
    ]
