# Generated by Django 2.2.17 on 2021-03-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTD', '0015_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='current',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='day',
            name='next',
        ),
    ]
